LudovicRousseau/pyscard

smartcard/util/__init__.py
test/test_util.py

When using toBytes on strings containing multiple lines, the results
are wrong. It used to work in pyscard 1.7.0 and before commit
1fd9457a79595061523dfa989f4c38e58b0bb801

Fix toBytes regression

---

setup.py

- Ensure that the `build_ext` task is called to generate SWIG .py files
before the Python copy step happens and we miss packaging and
installing the generated files.
- Wrap the `install` command for use with `pip`.  This is a bit of a
hack because setuptools looks at the stack frame to determine if it
was called from the setup function, and wrapping it would break that
behavior.
- Wrap the `bdist_egg` command for use with `easy_install`.
Bear in mind that I'm no setuptools / distutils expert.  This is the combined result of a bunch of Googling and some source diving into setuptools / distutils.  Interesting references about this problem include:
http://stackoverflow.com/questions/10559589/adding-output-file-to-python-extension
http://stackoverflow.com/questions/29477298/setup-py-run-build- …

Fix #15 - installing from `pip` and `easy_install`

---

Makefile
setup.py

- Ensure that the `build_ext` task is called before `build_py` to
generate SWIG .py files before the Python copy step happens and we
miss packaging and installing the generated files.
- Add Makefile target `test_install` for testing multiple build and
install methods on the active Python installation.
This is much cleaner; not sure why it didn't occur to me last night.  I think this should work with any install method entry point into setuptools because it's explicitly hooking into `build_py`, which should always be called.
The new Makefile target isn't the cleanest thing ever.  I just wanted an automated way to test the whole clean installation loop into my local Python install.

Fix #15 - installing from `pip` and `easy_install` (Take 2)

---

smartcard/CardMonitoring.py

Prevents duplicate error message printout.

Stop CardMonitor monitor thread after traceback print.

---

appveyor/run_with_env.cmd

Fixes issue #26.
Updated Appveyor environment configuration batch file to link correctly for Python versions 3.x (64bit).
(just copied the run_with_env.cmd file from https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor/run_with_env.cmd)

Fixed Appveyor environment config script to support 64bit Python 3.x.

---

setup.py

To install this package even when pcsclite is installed to a custom directory (with `./configure --prefix=/foo/bar`), the setup process checks if pkg-config returns valid compiler flags. It falls back to the default directories otherwise. As a result, `pip install pyscard` works with a customized installation of pcsclite.

Use include path from pkg-config

---

setup.py

This small changes allows to build pyscard under MSYS2/mingw environment on Windows:
```
python setup.py build
python setup.py install
```
The build process has errors, but it does complete. And the installation results in a working solution. 
Note: tested under mingw64 (32-bit not tested, but most likely works in the same way).

Removing platform sources for mingw under windows (building under msys2)

---

pyproject.toml

Alternative: include an error note to say to install swig from system package manager

Fix `swig` build dep

---

ChangeLog
setup.py
smartcard/ATR.py
smartcard/AbstractCardRequest.py
smartcard/CardService.py
smartcard/CardType.py
smartcard/Examples/scard-api/sample_getATR.py
smartcard/Examples/scard-api/sample_getAttrib.py
smartcard/Examples/scard-api/sample_listInterfaces.py
smartcard/Examples/wx/pcscdiag/pcscdiag.py
smartcard/Exceptions.py
smartcard/pcsc/PCSCCardConnection.py
smartcard/pcsc/PCSCPart10.py
smartcard/reader/ReaderFactory.py
smartcard/scard/PcscTypemaps.i
smartcard/scard/gemalto.ver
smartcard/scard/makefile
smartcard/scard/pyscard-reader.h
smartcard/scard/scard.i
smartcard/sw/ErrorCheckingChain.py
smartcard/sw/ISO7816_4ErrorChecker.py
smartcard/sw/ISO7816_8ErrorChecker.py
smartcard/test/framework/testcase_Card.py
smartcard/test/framework/testcase_ErrorChecking.py
smartcard/util/__init__.py
smartcard/wx/SimpleSCardApp.py
smartcard/wx/SimpleSCardAppFrame.py
smartcard/wx/__init__.py

* Fix typos found by the `typos` application
Please let me know if there's anything that shouldn't have been changed, and I'll undo those changes. :+1:

Fix typos found by `typos` application

---

.pylintrc
ChangeLog
INSTALL.md
smartcard/ReaderMonitoring.py
smartcard/guid.py
smartcard/pcsc/PCSCCardRequest.py
smartcard/pcsc/PCSCReader.py
smartcard/pyro/server/RemoteReaderServer.py
smartcard/reader/ReaderGroups.py
smartcard/scard/makefile
smartcard/test/framework/testcase_readergroups.py
smartcard/test/scard/testcase_geterrormessage.py
smartcard/ulist.py
test/test_ATR.py
tox.ini

* Remove Python 2 conditional code
* Add a tox `pylint` environment that mirrors the CI configuration.
> [!NOTE]
>
> No Python 3 / C compatibility functions were modified yet, but these need to be removed as well.
>
> These can be found later by searching the codebase for `PY_MAJOR_VERSION` and `PY_VERSION_HEX` references.

Remove Python 2 conditional code

---

.github/workflows/build.yml
ChangeLog

* Migrate CI to use the official Coveralls action
This lifts the restriction that only Linux coverage reports can be submitted, and helps prepare for standardized testing across all platforms.
I'll monitor the test runs to confirm that results are uploaded for both Linux and macOS.

Migrate CI to use the official Coveralls action

---

ChangeLog
src/smartcard/util/__init__.py

* Add missing GSM 03.38 symbols for decoding [[reference](https://en.wikipedia.org/wiki/GSM_03.38)]
* Re-order several symbols by codepoint

Add missing GSM 03.38 symbols for decoding

---

ChangeLog
src/smartcard/Examples/scard-api/sample_pinpad.py
src/smartcard/doc/user-guide.rst
src/smartcard/util/__init__.py
test/test_util.py

* Deprecate two utility functions and their aliases
* Add type annotations to utility functions
* Update utility function doc strings
* Use newer Python constructs to simplify remaining code

Deprecate several utility functions

---

tox.ini

~Also, modify the Makefile to use tox for coverage reporting.
Locally, `make coverage` runs in under 7 seconds.~
~If `make coverage` is not fast enough, I can remove the Makefile change.~
Makefile change removed.

Speed up coverage reporting by skipping package installation

---

src/smartcard/CardService.py
src/smartcard/PassThruCardService.py
src/smartcard/pcsc/PCSCContext.py
src/smartcard/pcsc/PCSCReader.py
src/smartcard/reader/ReaderFactory.py

This updates the codebase to use `staticmethod` decorators.

Migrate to `staticmethod` decorators

---

.github/workflows/build.yml
setup.py
tox.ini

Python 3.13 will be released in a few days (its third and final release candidate was published a few days ago).
This PR adds Python 3.13 to the tox test suite and to CI.

Test Python 3.13

---

pyproject.toml

This helps ensure that warnings that CPython ignores by default -- `ResourceWarning` -- or that warn of pending changes -- `DeprecationWarning` -- cause test suite failures in CI and can be addressed.
There are currently no warnings to address.

Escalate test suite warnings to errors

---

setup.py
src/smartcard/Synchronization.py
test/test_synchronization.py

Added
-----
* Add tests to bring `Synchronization.py` to 100% coverage
* Add type annotations to the synchronization primitives
* Add `typing_extensions` as a Python 3.9 requirement; this is needed to annotate that the `synchronized()` decorator takes a function with a certain set of parameter and return types and returns a function with the same parameter and return types
Changed
-------
* Make the synchronized function's `self` parameter explicit; this allows the `self` parameter to be type-annotated so the dependency on the `self.mutex` attribute is explicit
* Use the `self.mutex` lock as a context manager
* Support keyword arguments to synchronized functions
Fixed
-----
* Wrap synchronized functions correctly; previous behavior was to lose the function name and docstring
Removed …

Test and improve the synchronization code

---

src/smartcard/CardConnection.py
src/smartcard/CardConnectionDecorator.py
src/smartcard/System.py
src/smartcard/pcsc/PCSCCardConnection.py
src/smartcard/pcsc/PCSCReader.py
src/smartcard/reader/ReaderFactory.py

Fixed
-----
* Eliminate mutable default parameters from methods.
Because the parameters are passed to observers, it is possible for an observer to accidentally -- and permanently -- modify a default argument.
```python
observers = [lambda x: x.append("bad")]
def demo(groups=[]):
print(groups)
for observer in observers:
observer(groups)
demo()  # []
demo()  # ["bad"]
demo()  # ["bad", "bad"]
```

Eliminate mutable default parameters from methods

---

src/smartcard/Observer.py
test/test_observer.py

Added
-----
* Add tests for the `Observer.py` code, bringing the file up to 100% code coverage.
* Add type annotations to the Observer code.
Changed
-------
* Use the mutex lock as a context manager.
Previous behavior was to call `.acquire()` and `.release()`.
* Use `.copy()` instead of `[:]` syntax to make a copy of the observer list.
* Set `.changed` directly in `.notifyObservers()`.
Previous behavior was to call `.clearChanged()`. This resulted in multiple unnecessary functions calls due to the synchronization decorator and RLock re-acquisition.
* Use `super().__init__()` syntax.

Test and update the `Observer.py` code

---

ChangeLog
src/smartcard/ATR.py
test/test_ATR.py

Closes #214
Changed
-------
* Support "64" as an ATR baud rate adjustment integer (ISO 7816-3 2006).
Removed
-------
* Remove a trailing `"RFU"` value in the ATR clock rate mapping.
Clock rates are mapped using only 4 bits, meaning there are only 16 possible values. The trailing `"RFU"` value was the 17th value in the list.
Added
-----
* Add a single test that trivially checks the ATR mapping lengths.

Support "64" as an ATR baud rate adjustment integer

---

ChangeLog
src/smartcard/ATR.py
test/test_ATR.py

Added
-----
* Add `ATR.py` test cases. Code coverage of `ATR.py` is now 100%.
* Add type annotations to everything in `ATR.py`.
Changed
-------
* `SmartcardException` will be raised if the ATR is less than 2 bytes.
Fixed
-----
* The ATR `checksumOK` attribute is now guaranteed to exist. If there is no checksum, `checksumOK` will be set to `None`.
Previously, the attribute would only exist if a checksum existed.
* The checksum byte will now always be rendered if it exists.
Previously, if the checksum byte was `0x00`, it would not be rendered.
Removed
-------
* Remove the `__main__` code in `ATR.py`.
All of the ATRs are present in the test suite.
Deprecated
----------
* The ATR hasTA/hasTB/hasTC/hasTD attributes are deprecated.
Users may compare items in the TA/TB/TC/TD attributes to …

Test, fix, and simplify ATR parsing
